-- MySQL Script generated by MySQL Workbench
-- Thu Dec 17 12:32:53 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema avengor_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `avengor_db` ;

-- -----------------------------------------------------
-- Schema avengor_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `avengor_db` DEFAULT CHARACTER SET utf8 ;
USE `avengor_db` ;

-- -----------------------------------------------------
-- Table `avengor_db`.`Civils`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avengor_db`.`Civils` ;

CREATE TABLE IF NOT EXISTS `avengor_db`.`Civils` (
  `id_Civil` INT NOT NULL AUTO_INCREMENT,
  `Password` VARCHAR(255) NULL,
  `Nom` VARCHAR(45) NULL,
  `Prenom` VARCHAR(45) NULL,
  `Civilite` VARCHAR(3) NULL,
  `Adresse` VARCHAR(255) NULL,
  `Email` VARCHAR(100) NULL,
  `Tel` VARCHAR(45) NULL,
  `Nationalite` VARCHAR(75) NULL,
  `DateDeNaissance` DATE NULL,
  `DateDeDeces` DATETIME NULL,
  `Orga` VARCHAR(45) NULL,
  `Commentaire` VARCHAR(255) NULL,
  `DateAjout` DATETIME NULL,
  `DateDerniereModif` DATETIME NULL,
  `NbIncidentsDeclare` INT NULL,
  `NbMissionVictime` INT NULL,
  PRIMARY KEY (`id_Civil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avengor_db`.`Organisations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avengor_db`.`Organisations` ;

CREATE TABLE IF NOT EXISTS `avengor_db`.`Organisations` (
  `id_Organisations` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(255) NULL,
  `Adresse` VARCHAR(255) NULL,
  `Dirigeant` INT NOT NULL,
  `Commentaire` VARCHAR(255) NULL,
  `DateAjout` DATETIME NULL,
  `DATEDerniereModif` DATETIME NULL,
  `NbIncidentsDeclares` INT NULL,
  `NbMissionsImplique` INT NULL,
  PRIMARY KEY (`id_Organisations`),
  INDEX `fk_Organisations_Civils1_idx` (`Dirigeant` ASC) VISIBLE,
  CONSTRAINT `fk_Organisations_Civils1`
    FOREIGN KEY (`Dirigeant`)
    REFERENCES `avengor_db`.`Civils` (`id_Civil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avengor_db`.`Incidents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avengor_db`.`Incidents` ;

CREATE TABLE IF NOT EXISTS `avengor_db`.`Incidents` (
  `id_Incidents` INT NOT NULL AUTO_INCREMENT,
  `Adresse` VARCHAR(255) NULL,
  `TypeIncident` VARCHAR(255) NULL,
  `id_Civils` INT NULL,
  `Ennemis` INT NULL,
  `Mission` TINYINT NULL,
  `InfoComplementaire` VARCHAR(1500) NULL,
  PRIMARY KEY (`id_Incidents`),
  INDEX `fk_Incidents_Civils1_idx` (`id_Civils` ASC) VISIBLE,
  CONSTRAINT `fk_Incidents_Civils1`
    FOREIGN KEY (`id_Civils`)
    REFERENCES `avengor_db`.`Civils` (`id_Civil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avengor_db`.`Missions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avengor_db`.`Missions` ;

CREATE TABLE IF NOT EXISTS `avengor_db`.`Missions` (
  `id_Mission` INT NOT NULL AUTO_INCREMENT,
  `Titre` VARCHAR(100) NULL,
  `DateDebut` DATETIME NULL,
  `DateFin` DATETIME NULL,
  `Niveaux` INT NULL,
  `Urgence` INT NULL,
  `id_Incidents` INT NOT NULL,
  PRIMARY KEY (`id_Mission`),
  INDEX `fk_Missions_Incidents1_idx` (`id_Incidents` ASC) VISIBLE,
  CONSTRAINT `fk_Missions_Incidents1`
    FOREIGN KEY (`id_Incidents`)
    REFERENCES `avengor_db`.`Incidents` (`id_Incidents`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avengor_db`.`Super_heros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avengor_db`.`Super_heros` ;

CREATE TABLE IF NOT EXISTS `avengor_db`.`Super_heros` (
  `id_SuperHeros` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(75) NULL,
  `IdentiteSecretes` INT NULL,
  `Pouvoir` VARCHAR(45) NULL,
  `Point_faible` VARCHAR(255) NULL,
  `Score` FLOAT NULL,
  `Commentaire` VARCHAR(255) NULL,
  PRIMARY KEY (`id_SuperHeros`),
  INDEX `fk_Super-heros_Civils1_idx` (`IdentiteSecretes` ASC) VISIBLE,
  CONSTRAINT `fk_Super-heros_Civils1`
    FOREIGN KEY (`IdentiteSecretes`)
    REFERENCES `avengor_db`.`Civils` (`id_Civil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avengor_db`.`Rapport de mission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avengor_db`.`Rapport de mission` ;

CREATE TABLE IF NOT EXISTS `avengor_db`.`Rapport de mission` (
  `id_Rapport` INT NOT NULL AUTO_INCREMENT,
  `id_Mission` INT NOT NULL,
  PRIMARY KEY (`id_Rapport`),
  INDEX `fk_Rapport de mission_Missions1_idx` (`id_Mission` ASC) VISIBLE,
  CONSTRAINT `fk_Rapport de mission_Missions1`
    FOREIGN KEY (`id_Mission`)
    REFERENCES `avengor_db`.`Missions` (`id_Mission`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avengor_db`.`Crise`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avengor_db`.`Crise` ;

CREATE TABLE IF NOT EXISTS `avengor_db`.`Crise` (
  `id_Crise` INT NOT NULL AUTO_INCREMENT,
  `Type` INT NULL,
  `id_Mission` INT NULL,
  `Commentaire` VARCHAR(255) NULL,
  `Vilains` INT NULL,
  `id_Civil` INT NULL,
  PRIMARY KEY (`id_Crise`),
  INDEX `fk_Crise_Civils1_idx` (`id_Civil` ASC) VISIBLE,
  INDEX `fk_Crise_Missions1_idx` (`id_Mission` ASC) VISIBLE,
  CONSTRAINT `fk_Crise_Civils1`
    FOREIGN KEY (`id_Civil`)
    REFERENCES `avengor_db`.`Civils` (`id_Civil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Crise_Missions1`
    FOREIGN KEY (`id_Mission`)
    REFERENCES `avengor_db`.`Missions` (`id_Mission`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avengor_db`.`Litige`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avengor_db`.`Litige` ;

CREATE TABLE IF NOT EXISTS `avengor_db`.`Litige` (
  `id_Litige` INT NOT NULL AUTO_INCREMENT,
  `id_Crise` INT NULL,
  `Mission` INT NULL,
  `Cout` FLOAT NULL,
  `Photo` VARCHAR(255) NULL,
  PRIMARY KEY (`id_Litige`),
  INDEX `fk_Litige_Crise1_idx` (`id_Crise` ASC) VISIBLE,
  CONSTRAINT `fk_Litige_Crise1`
    FOREIGN KEY (`id_Crise`)
    REFERENCES `avengor_db`.`Crise` (`id_Crise`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avengor_db`.`Satisfaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avengor_db`.`Satisfaction` ;

CREATE TABLE IF NOT EXISTS `avengor_db`.`Satisfaction` (
  `id_Satisfaction` INT NOT NULL AUTO_INCREMENT,
  `id_Civil` INT NOT NULL,
  `id_Incidents` INT NULL,
  `id_Mission` INT NULL,
  `Missions` INT NULL,
  `Message` VARCHAR(1500) NULL,
  `Note` INT NULL,
  `Commentaire` VARCHAR(255) NULL,
  PRIMARY KEY (`id_Satisfaction`),
  INDEX `fk_Satisfaction_Civils1_idx` (`id_Civil` ASC) VISIBLE,
  INDEX `fk_Satisfaction_Incidents1_idx` (`id_Incidents` ASC) VISIBLE,
  INDEX `fk_Satisfaction_Missions1_idx` (`id_Mission` ASC) VISIBLE,
  CONSTRAINT `fk_Satisfaction_Civils1`
    FOREIGN KEY (`id_Civil`)
    REFERENCES `avengor_db`.`Civils` (`id_Civil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Satisfaction_Incidents1`
    FOREIGN KEY (`id_Incidents`)
    REFERENCES `avengor_db`.`Incidents` (`id_Incidents`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Satisfaction_Missions1`
    FOREIGN KEY (`id_Mission`)
    REFERENCES `avengor_db`.`Missions` (`id_Mission`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avengor_db`.`Super_vilains`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avengor_db`.`Super_vilains` ;

CREATE TABLE IF NOT EXISTS `avengor_db`.`Super_vilains` (
  `id_SuperVilains` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(75) NULL,
  `IdentiteSecretes` INT NULL,
  `Pouvoir` VARCHAR(45) NULL,
  `Point_faible` VARCHAR(45) NULL,
  `Score` FLOAT NULL,
  `Commentaire` VARCHAR(255) NULL,
  PRIMARY KEY (`id_SuperVilains`),
  INDEX `fk_Super-vilains_Civils_idx` (`IdentiteSecretes` ASC) VISIBLE,
  CONSTRAINT `fk_Super-vilains_Civils`
    FOREIGN KEY (`IdentiteSecretes`)
    REFERENCES `avengor_db`.`Civils` (`id_Civil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avengor_db`.`CivilsOrganisation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avengor_db`.`CivilsOrganisation` ;

CREATE TABLE IF NOT EXISTS `avengor_db`.`CivilsOrganisation` (
  `Organisation` INT NOT NULL,
  `Civil` INT NOT NULL,
  PRIMARY KEY (`Organisation`, `Civil`),
  INDEX `fk_Organisations_has_Civils_Civils1_idx` (`Civil` ASC) VISIBLE,
  INDEX `fk_Organisations_has_Civils_Organisations1_idx` (`Organisation` ASC) VISIBLE,
  CONSTRAINT `fk_Organisations_has_Civils_Organisations1`
    FOREIGN KEY (`Organisation`)
    REFERENCES `avengor_db`.`Organisations` (`id_Organisations`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Organisations_has_Civils_Civils1`
    FOREIGN KEY (`Civil`)
    REFERENCES `avengor_db`.`Civils` (`id_Civil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avengor_db`.`TRef`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avengor_db`.`TRef` ;

CREATE TABLE IF NOT EXISTS `avengor_db`.`TRef` (
  `id_TRef` INT NOT NULL AUTO_INCREMENT,
  `TypeRef` VARCHAR(10) NULL,
  `0` VARCHAR(45) NULL,
  PRIMARY KEY (`id_TRef`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avengor_db`.`SH_Mission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avengor_db`.`SH_Mission` ;

CREATE TABLE IF NOT EXISTS `avengor_db`.`SH_Mission` (
  `Super_heros_id_SuperHeros` INT NOT NULL,
  `Missions_id_Mission` INT NOT NULL,
  PRIMARY KEY (`Super_heros_id_SuperHeros`, `Missions_id_Mission`),
  INDEX `fk_Super-heros_has_Missions_Missions1_idx` (`Missions_id_Mission` ASC) VISIBLE,
  INDEX `fk_Super-heros_has_Missions_Super-heros1_idx` (`Super_heros_id_SuperHeros` ASC) VISIBLE,
  CONSTRAINT `fk_Super-heros_has_Missions_Super-heros1`
    FOREIGN KEY (`Super_heros_id_SuperHeros`)
    REFERENCES `avengor_db`.`Super_heros` (`id_SuperHeros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Super-heros_has_Missions_Missions1`
    FOREIGN KEY (`Missions_id_Mission`)
    REFERENCES `avengor_db`.`Missions` (`id_Mission`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
